security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:900}
    refresh-expiration-seconds: ${JWT_REFRESH_EXPIRATION_SECONDS:604800}
    issuer: ${JWT_ISSUER:secure-auth-api}

spring:
  application:
    name: secure-auth-api

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never

  flyway:
    enabled: true

logging:
  level:
    root: INFO
